/**:
  ros__parameters:
    port: "/dev/ttyACM0"
    brake_max: 200000.0
    brake_min: -20000.0
    current_max: 0.0
    current_min: 0.0
    duty_cycle_max: 0.5
    duty_cycle_min: 0.05
    position_max: 0.0
    position_min: 0.0
    servo_max: 0.8
    servo_min: 0.2
    speed_max:  100000.0 #23250.0
    speed_min: -100000.0 #-23250.0
    
    speed_to_erpm_gain: 2480.0
    speed_to_erpm_offset: 0.0
    steering_angle_to_servo_gain: -0.895
    steering_angle_to_servo_offset: 0.5

twist_to_ackermann_node:
  ros__parameters:
    twist_cmd_topic: /cmd_vel
    ackermann_cmd_topic: /ackermann_cmd
    wheelbase: .305
    frame_id: odom

# No longer needed, all parameters are shared
# ackermann_to_vesc_node:
#   ros__parameters:

vesc_to_odom_node:
  ros__parameters:
    odom_frame: odom
    base_frame: base_link
    # publish odom to base link tf
    publish_tf: false
    use_servo_cmd_to_calc_angular_velocity: false
    # car wheelbase is about 25cm
    wheelbase: .305

# No longer needed, all parameters are shared
# vesc_driver:
#   ros__parameters:

# throttle_interpolator:
#   ros__parameters:
#     rpm_input_topic: commands/motor/unsmoothed_speed
#     rpm_output_topic: commands/motor/speed
#     servo_input_topic: commands/servo/unsmoothed_position
#     servo_output_topic: commands/servo/position

#     # servo smoother - limits acceleration and smooths anything above limit
#     max_acceleration: 2.5 # meters/second^2
#     throttle_smoother_rate: 75.0 # messages/sec
#     # servo smoother - limits rotation speed and smooths anything above limit
#     max_servo_speed: 3.2 # radians/second
#     servo_smoother_rate: 75.0 # messages/sec